version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WaitTime"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kt2q8amnrpy3"
s3_prefix = "WaitTime"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
