AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  StudyEdgeOfficeHours

  Sample SAM Template for StudyEdgeOfficeHours

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WaitTimeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wait_time/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        WaitTime:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wait_time
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WaitTimeApi:
    Description: "API Gateway endpoint URL for Prod stage for Wait Time function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wait_time/"
  WaitTimeFunction:
    Description: "Wait Time Lambda Function ARN"
    Value: !GetAtt WaitTimeFunction.Arn
  WaitTimeFunctionIamRole:
    Description: "Implicit IAM Role created for Wait Time function"
    Value: !GetAtt WaitTimeFunctionRole.Arn

